---
name: "CI"
on: # yamllint disable
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-24.04"
        type: string
      all-tests:
        description: "Test all versions of Nautobot and Python"
        required: false
        default: false
        type: boolean

jobs:
  tests_partial:
    # Only run the tests for a subset of versions of Nautobot and Python
    if: ${{ inputs.all-tests == false }}
    uses: ./.github/workflows/tests.yml
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        nautobot-version:
          - "stable"
    with:
      runs-on: "${{ inputs.runs-on }}"
      python-version: "${{ matrix.python-version }}"
      nautobot-version: "${{ matrix.nautobot-version }}"
  tests_full:
    # Run the tests for all supported versions of Nautobot and Python
    if: ${{ inputs.all-tests == true }}
    uses: ./.github/workflows/tests.yml
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        nautobot-version:
          - "2.0"
          - "2.1"
          - "2.2"
          - "2.3"
          - "2.4"
          - "stable"
    with:
      runs-on: "${{ inputs.runs-on }}"
      python-version: "${{ matrix.python-version }}"
      nautobot-version: "${{ matrix.nautobot-version }}"
